# Generated by Django 3.0.6 on 2020-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=200)),
                ('kind_of_item', models.CharField(max_length=200)),
                ('price_of_item', models.CharField(max_length=200)),
                ('when_added', models.DateTimeField(max_length=200)),
            ],
        ),
    ]
